### ISSUE TITLE
Request always times out.

### ISSUE THREAD

**Issue by upedd** [kmpm/node-mcquery#15]
Whenever im pinging hypixel or local server request always times out.

`Connecting to server
error connecting Error: Request timeout
    at Timeout._onTimeout (/mnt/c/Users/MiłoszK/Desktop/Programowanie/Discord/server-manager/node_modules/mcquery/lib/index.js:349:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Comment by kmpm** [comment]
That's usually because the server is not listening. Have you enabled the protocol in the server and using the same port in both client and server?

**Comment by upedd** [comment]
But server gives response when using an external api https://api.mcsrvstat.us/

**Comment by kmpm** [comment]
Can you post an example of such a response, version number of your mc server and a copy of the server config.
Just so that I have some more information to work with.

**Comment by upedd** [comment]
1.12.2 modded sevtech ages modpack. server config:
 ```#Minecraft server properties
#Sat Jun 13 12:36:23 UTC 2020
spawn-protection=16
max-tick-time=60000
query.port=25565
generator-settings=
force-gamemode=true
allow-nether=true
gamemode=0
dc_preset=notSet
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=false
level-type=quark_realistic
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
use-native-transport=true
motd=\u00A7d\u00A7oSevTech\: Ages Server\u00A7r - \u00A74v3.1.2
enable-rcon=false
```

response from an api: 
```
// 20200613154820
// https://api.mcsrvstat.us/2/35.242.214.235

{
  "ip": "35.242.214.235",
  "port": 25565,
  "debug": {
    "ping": true,
    "query": false,
    "srv": false,
    "querymismatch": false,
    "ipinsrv": false,
    "cnameinsrv": false,
    "animatedmotd": false,
    "cachetime": 0,
    "apiversion": 2
  },
  "motd": {
    "raw": [
      "§d§oSevTech: Ages Server§r - §4v3.1.2"
    ],
    "clean": [
      "SevTech: Ages Server - v3.1.2"
    ],
    "html": [
      "<span style=\"color: #FF55FF\"><span style=\"font-style: italic;\">SevTech: Ages Server</span></span> - <span style=\"color: #AA0000\">v3.1.2</span>"
    ]
  },
  "players": {
    "online": 0,
    "max": 20
  },
  "version": "1.12.2",
  "online": true,
  "protocol": 340,
  "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACqElEQVR42u2aTUgbQRSAF/GUi4UeWiwoQg9SvBRRRARLe2pz0F7qsRdvvbUHS9WAQs+lhZb20kNP/iTRKiVCg0JBEFJPLVEoHqoQLMVsrG2aBpJXZ0KkiZN1ZnezebN9H7yDm5W89+XNzGYmhkEQBEEQBEEQ3hBJg3T4hsVfoFR4dbD/15FmJ0WLImqCP1tdNf7r4tFL8KJ4tBIkEz+/bEItzi2amkqQSJZNirKMbv7UR4LMbG8XKQELR4D603cK7i6oc/H4JVgk1DRvLaDn1RoYk2EwHs3DyOyG5b1s4tROQC0m4p/BCEWE4agLPJ8LoqZy+2+mzJrFnyXBmD1A1gXhNLS+y8DbVL4i0Xwuy+PMcT02oyShUCziEMCSeTl+D8aG+uHh7QHleBDsgfS3VEmCahc0TEC5/cKl1mYF3L/ZbUvAxJ3rJwXdjSQ0ECB4o+D6ke0l7Wu2cDrx6SWkAlxe43MFiyJcENDx5hN4JqBv7Ye7DzTR0grBJjsRj7d/+1zAcVx7/QHZ06DLQ8CYs0h+Lo30cdjlSdCO0MZ/NZ45kEq088pVaL10GS5c7IDJ0JR0QVa0xzK49gZESSYSH6GtvVMYTpCZ+FAIKBd7Kzh86ppdCc93cjj3CUXFs7aPx1dPrpmZTKnVj29nr7OhUdfCGy0gEAjwYgcHb/Brvb39XEhZgKgLWHvH9vM8ut4fWq8Q2AWsrMR48cnkFi+aBRsOu7t7vDtEAkLJrJ5b5SIB/9LX3VLxN1sNRAKUdn4x7hB//1MUCqjm6bMXFfc8+ZLj3yr1PyxhW1BengSRABKAcGcYU/ENOSEiAQqtaWfIqLwHegGiOaQ6nHaZVgLqMcx8KUB26GAdAs1ufDI6H5G7cw55iPy3hF61pK9/UUoQBEEQBEEQnvEXUSg2GSD9RecAAAAASUVORK5CYII=",
  "mods": {
    "names": [
      "abyssalcraft",
      "acintegration",
      "actuallyadditions",
      "actuallybaubles",
      "advancedmortars",
      "advgenerators",
      "animalium",
      "antiqueatlas",
      "appleskin",
      "appliedenergistics2",
      "armoreablemobs",
      "aroma1997core",
      "aromabackup",
      "aromabackuprecovery",
      "astikorcarts",
      "astralsorcery",
      "autoreglib",
      "base",
      "baubles",
      "bdlib",
      "bedrockbgone",
      "beneath",
      "betterbuilderswands",
      "betterwithaddons",
      "betterwithlib",
      "betterwithmods",
      "bibliocraft",
      "bloodmagic",
      "bnbgamingcore",
      "bnbgaminglib",
      "bonsaitrees",
      "bookshelf",
      "buildcraftbuilders",
      "buildcraftcore",
      "buildcraftfactory",
      "buildcraftlib",
      "buildcraftrobotics",
      "buildcraftsilicon",
      "buildcrafttransport",
      "buildinggadgets",
      "car",
      "carryon",
      "cd4017be_lib",
      "ceramics",
      "chameleon",
      "charcoalblock",
      "chargers",
      "chisel",
      "chiselsandbits",
      "clumps",
      "codechickenlib",
      "commoncapabilities",
      "compactmachines3",
      "conarm",
      "contenttweaker",
      "cookingforblockheads",
      "crafttweaker",
      "crafttweakerjei",
      "cucumber",
      "cyclicmagic",
      "cyclopscore",
      "darkutils",
      "death_compass",
      "despawningspawners",
      "dimensionalcontrol",
      "dimstages",
      "dungpipe",
      "elevatorid",
      "emberroot",
      "enderstorage",
      "enderutilities",
      "environmentaltech",
      "extendedcrafting",
      "extraplanets",
      "farmingforblockheads",
      "farseek",
      "fastbench",
      "fastfurnace",
      "fat_cat",
      "ferdinandsflowers",
      "findme",
      "FML",
      "foamfix",
      "foamfixcore",
      "forge",
      "forgelin",
      "forgemultipartcbe",
      "galacticraftcore",
      "galacticraftplanets",
      "galacticrafttweaker",
      "gamestages",
      "geolosys",
      "gobblecore",
      "guideapi",
      "harvest",
      "horsepower",
      "huntingdim",
      "igwmod",
      "immcraft",
      "immersiveengineering",
      "immersivepetroleum",
      "immersivetech",
      "improvedbackpacks",
      "incontrol",
      "indlog",
      "industrialforegoing",
      "infoaccessories",
      "integrateddynamics",
      "integrateddynamicscompat",
      "inventorytweaks",
      "ironbackpacks",
      "ironchest",
      "ironjetpacks",
      "itemstages",
      "ivtoolkit",
      "jaff",
      "jarm",
      "jei",
      "jeid",
      "jeidsi",
      "journeymap",
      "kleeslabs",
      "lex",
      "lttweaker",
      "magma_monsters",
      "mantle",
      "mcjtylib_ng",
      "mcp",
      "mekanism",
      "mekatweaks",
      "mercurius",
      "micdoodlecore",
      "microblockcbe",
      "minecraft",
      "minecraftmultipartcbe",
      "mjrlegendslib",
      "mobends",
      "mobstages",
      "mob_grinding_utils",
      "modtweaker",
      "modularmachinery",
      "modularrouters",
      "morpheus",
      "movillages",
      "mpbasic",
      "mputils",
      "mtlib",
      "multiblockstages",
      "mundaneredstone",
      "mystagradcompat",
      "mysticalagradditions",
      "mysticalagriculture",
      "natura",
      "naturescompass",
      "nex",
      "noworldgen5you",
      "nutrition",
      "oeintegration",
      "oreexcavation",
      "orestages",
      "overloaded",
      "pickletweaks",
      "placebo",
      "playerbosses",
      "playerskins",
      "pneumaticcraft",
      "poweradapters",
      "prestige",
      "primal",
      "primalchests",
      "primal_tech",
      "progressiontweaks",
      "prospectors",
      "quantumstorage",
      "quark",
      "quickleafdecay",
      "rangedpumps",
      "realdrops",
      "reborncore",
      "rebornstorage",
      "reccomplex",
      "recipestages",
      "redstoneflux",
      "refinedstorage",
      "refinedstorageaddons",
      "rftools",
      "rftoolscontrol",
      "roadrunner",
      "rustic",
      "samsocean",
      "sasit",
      "scannable",
      "sevtweaks",
      "sev_tweaks_npc",
      "simpleautorun",
      "simplegenerators",
      "simplyarrows",
      "smoothfontcore",
      "spartanshields",
      "spatialservermod",
      "stevescarts",
      "stg",
      "storagedrawers",
      "storagenetwork",
      "streams",
      "supersoundmuffler",
      "tallgates",
      "tcomplement",
      "tconstruct",
      "teslacorelib",
      "teslacorelib_registries",
      "thebetweenlands",
      "thirstybottles",
      "tinkerstages",
      "tinkertoolleveling",
      "togetherforever",
      "tombstone",
      "totemic",
      "tothebatpoles",
      "translocators",
      "traverse",
      "triumph",
      "trumpetskeleton",
      "tumbleweed",
      "twilightforest",
      "universalmodifiers",
      "uppers",
      "valkyrielib",
      "vc",
      "vtt",
      "waddles",
      "waila",
      "wailastages",
      "wanionlib",
      "watercontrolextreme",
      "waterstrainer",
      "wawla",
      "weirdinggadget",
      "wildcrops",
      "witherskelefix",
      "wopper",
      "xnet",
      "ynot",
      "yoyos",
      "zenstages"
    ],
    "raw": {
      "0": "minecraft 1.12.2",
      "1": "mcp 9.42",
      "2": "FML 8.0.99.99",
      "3": "forge 14.23.5.2838",
      "4": "ivtoolkit 1.3.3-1.12",
      "5": "micdoodlecore ",
      "6": "smoothfontcore mc1.12.2-2.0",
      "7": "bnbgamingcore 0.11.0",
      "8": "foamfixcore 7.7.4",
      "9": "movillages 1.5.4",
      "10": "charcoalblock 1.1",
      "11": "advancedmortars 1.12.2-1.6.23",
      "12": "crafttweaker 4.1.18",
      "13": "mtlib 3.0.6",
      "14": "modtweaker 4.0.17",
      "15": "jei 4.15.0.283",
      "16": "abyssalcraft 1.9.8",
      "17": "chisel MC1.12.2-0.2.1.35",
      "18": "mantle 1.12-1.3.3.55",
      "19": "twilightforest 3.8.689",
      "20": "tconstruct 1.12.2-2.12.0.135",
      "21": "acintegration 1.8.1",
      "22": "fastbench 1.7.2",
      "23": "actuallyadditions 1.12.2-r149",
      "24": "baubles 1.5.2",
      "25": "actuallybaubles 1.1",
      "26": "animalium 0.3.8",
      "27": "antiqueatlas 4.5.1",
      "28": "base 3.13.0",
      "29": "contenttweaker 1.12.2-4.9.1",
      "30": "immersiveengineering 0.12-89",
      "31": "geolosys 2.2.6",
      "32": "cyclicmagic 1.19.11",
      "33": "redstoneflux 2.1.0",
      "34": "mekanism 1.12.2-9.7.9.380",
      "35": "natura 1.12.2-4.3.2.69",
      "36": "traverse 1.6.0",
      "37": "betterwithmods 1.12-2.3.20-1027",
      "38": "appleskin 1.0.9",
      "39": "appliedenergistics2 rv6-stable-6",
      "40": "armoreablemobs 1.1.2",
      "41": "aroma1997core 2.0.0.2",
      "42": "aromabackup 2.1.1.4",
      "43": "aromabackuprecovery 2.1.1.4",
      "44": "astikorcarts 1.12.2-0.1.2.7",
      "45": "astralsorcery 1.10.19",
      "46": "quark r1.5-158",
      "47": "autoreglib 1.3-31",
      "48": "bdlib 1.14.3.12",
      "49": "bedrockbgone 5.0.8",
      "50": "betterwithaddons 0.50-hotfix",
      "51": "betterbuilderswands 0.13.2",
      "52": "betterwithlib ${version}",
      "53": "bibliocraft 2.4.5",
      "54": "waila 1.8.26",
      "55": "modularrouters 1.12.2-3.2.1",
      "56": "guideapi 1.12-2.1.8-63",
      "57": "bloodmagic 1.12.2-2.4.1-103",
      "58": "bnbgaminglib 2.17.6",
      "59": "bonsaitrees 1.1.3",
      "60": "bookshelf 2.3.581",
      "61": "buildcraftlib 7.99.24.1",
      "62": "buildcraftcore 7.99.24.1",
      "63": "buildcraftbuilders 7.99.24.1",
      "64": "buildcraftfactory 7.99.24.1",
      "65": "buildcraftrobotics 7.99.24.1",
      "66": "buildcrafttransport 7.99.24.1",
      "67": "buildcraftsilicon 7.99.24.1",
      "68": "buildinggadgets 2.6.8",
      "69": "car 1.2.12",
      "70": "gamestages 2.0.115",
      "71": "carryon 1.12.1",
      "72": "cd4017be_lib 6.4.6",
      "73": "ceramics 1.12-1.3.7",
      "74": "chameleon 1.12-4.1.3",
      "75": "chargers 1.2.0.4",
      "76": "chiselsandbits 14.33",
      "77": "clumps 3.1.2",
      "78": "codechickenlib 3.2.2.353",
      "79": "cyclopscore 1.3.0",
      "80": "commoncapabilities 2.4.1",
      "81": "refinedstorage 1.6.14",
      "82": "compactmachines3 3.0.18",
      "83": "conarm 1.2.4",
      "84": "cookingforblockheads 6.4.70",
      "85": "crafttweakerjei 2.0.3",
      "86": "cucumber 1.1.3",
      "87": "darkutils 1.8.226",
      "88": "death_compass 0.0.3",
      "89": "despawningspawners 1.1",
      "90": "dimensionalcontrol 2.11.0",
      "91": "dimstages 2.0.23",
      "92": "dungpipe 1.0",
      "93": "elevatorid 1.4.2",
      "94": "emberroot 1.3.9",
      "95": "enderstorage 2.4.5.135",
      "96": "enderutilities 0.7.12",
      "97": "valkyrielib 1.12.2-2.0.20.1",
      "98": "environmentaltech 1.12.2-2.0.20.1",
      "99": "extendedcrafting 1.5.4",
      "100": "galacticraftcore 4.0.2.211",
      "101": "galacticraftplanets 4.0.2.211",
      "102": "mjrlegendslib 1.12.2-1.1.8",
      "103": "extraplanets 1.12.2-0.5.3",
      "104": "farmingforblockheads 3.1.26",
      "105": "farseek 2.3.2",
      "106": "fastfurnace 1.3.1",
      "107": "fat_cat 0.0.5",
      "108": "ferdinandsflowers 1.10.4.1",
      "109": "findme 1.1.0",
      "110": "foamfix 0.10.5-1.12.2",
      "111": "forgelin 1.8.2",
      "112": "forgemultipartcbe 2.6.1.81",
      "113": "microblockcbe 2.6.1.81",
      "114": "minecraftmultipartcbe 2.6.1.81",
      "115": "galacticrafttweaker 1.12.2-1.0.3",
      "116": "advgenerators 0.9.20.12",
      "117": "gobblecore 1.12-0.1.6.35",
      "118": "harvest 1.12-1.2.7-20",
      "119": "horsepower 2.6.4",
      "120": "huntingdim 1.0.39",
      "121": "igwmod 1.4.4-15",
      "122": "mcjtylib_ng 3.5.3",
      "123": "immcraft 1.6.0",
      "124": "immersivepetroleum 1.1.9",
      "125": "immersivetech 1.3.10",
      "126": "improvedbackpacks 1.12.2-1.4.0.0",
      "127": "incontrol 3.9.10",
      "128": "indlog 1.3.3",
      "129": "teslacorelib 1.0.15",
      "130": "industrialforegoing 1.12.2-1.12.2",
      "131": "infoaccessories 1.0.11",
      "132": "integrateddynamics 1.0.14",
      "133": "integrateddynamicscompat 1.0.0",
      "134": "inventorytweaks 1.64+dev.146.2180b27",
      "135": "ironbackpacks 1.12.2-3.0.8-12",
      "136": "ironchest 1.12.2-7.0.67.844",
      "137": "ironjetpacks 1.1.0",
      "138": "itemstages 2.0.49",
      "139": "jeid 1.0.2-26",
      "140": "jeidsi 1.2.1.29",
      "141": "journeymap 1.12.2-5.5.4",
      "142": "jarm 1.1.2",
      "143": "jaff 1.7_for_1.12",
      "144": "kleeslabs 5.4.11",
      "145": "lex 1.0.8",
      "146": "lttweaker 1.1.14",
      "147": "magma_monsters 0.3.0",
      "148": "mekatweaks 1.0.0-3",
      "149": "mercurius 1.0.6",
      "150": "mobends 0.24",
      "151": "mob_grinding_utils 0.3.13",
      "152": "mobstages 2.0.13",
      "153": "modularmachinery 1.9.5",
      "154": "morpheus 1.12.2-3.5.106",
      "155": "mputils 1.5.6",
      "156": "mpbasic 1.4.7",
      "157": "multiblockstages 1.1.1",
      "158": "mundaneredstone 1.1.4",
      "159": "mysticalagriculture 1.7.5",
      "160": "mysticalagradditions 1.3.2",
      "161": "mystagradcompat 1.2",
      "162": "naturescompass 1.5.1",
      "163": "nex 2.0.8",
      "164": "noworldgen5you 1.0.6",
      "165": "nutrition 4.3.0",
      "166": "samsocean 1.0.1",
      "167": "oreexcavation 1.4.140",
      "168": "oeintegration 2.3.4",
      "169": "orestages 2.0.37",
      "170": "overloaded 0.0.57",
      "171": "pickletweaks 2.1.3",
      "172": "placebo 1.6.0",
      "173": "playerbosses 1.0",
      "174": "playerskins 1.0.4",
      "175": "pneumaticcraft 1.12.2-0.11.1-361",
      "176": "poweradapters 1.0.9",
      "177": "prestige 1.1.30",
      "178": "primalchests 1.0.3",
      "179": "rustic 1.1.0",
      "180": "thebetweenlands 3.4.6",
      "181": "primal 0.6.104",
      "182": "progressiontweaks 1.12.2-0.3.40",
      "183": "prospectors 1.0.2",
      "184": "reborncore 3.13.12.447",
      "185": "quantumstorage 4.6.8",
      "186": "quickleafdecay 1.2.4",
      "187": "rangedpumps 0.5",
      "188": "realdrops 1.2.14",
      "189": "rebornstorage 1.0.0",
      "190": "recipestages 1.1.1",
      "191": "reccomplex 1.4.8.2",
      "192": "refinedstorageaddons 0.4.4",
      "193": "rftools 7.71",
      "194": "rftoolscontrol 2.0.2",
      "195": "roadrunner 1.0.1",
      "196": "scannable 1.6.3.24",
      "197": "sevtweaks 0.3.1-25",
      "198": "sev_tweaks_npc 0.0.4",
      "199": "simpleautorun 1.12.1-1.2",
      "200": "simplegenerators 1.12.2-2.0.20.2",
      "201": "storagenetwork 1.7.6",
      "202": "simplyarrows 1.0.4",
      "203": "spartanshields 1.5.4",
      "204": "spatialservermod 1.3",
      "205": "stevescarts 2.4.30.134",
      "206": "stg 1.12.2-1.2.3",
      "207": "storagedrawers 1.12-5.3.5",
      "208": "streams 0.4.7",
      "209": "sasit 1.1.14",
      "210": "supersoundmuffler 1.0.2.10",
      "211": "tallgates 1.0.0",
      "212": "beneath 1.5.1",
      "213": "thirstybottles 1.1.4",
      "214": "tcomplement 1.12.2-0.4.1",
      "215": "tinkerstages 2.0.17",
      "216": "tinkertoolleveling 1.12.2-1.1.0.DEV.b23e769",
      "217": "togetherforever 1.0.2",
      "218": "tombstone 3.5.3",
      "219": "totemic 1.12.2-0.11.6",
      "220": "tothebatpoles 1.12.2-1.1.0.1",
      "221": "translocators 2.5.1.77",
      "222": "triumph 3.17.0",
      "223": "trumpetskeleton 1.12-1.0.2.1",
      "224": "tumbleweed 1.11-0.4.5",
      "225": "uppers 0.0.6",
      "226": "universalmodifiers 1.12.2-1.0.16.1",
      "227": "vc 5.9.13",
      "228": "vtt 0.6.4",
      "229": "waddles 0.6.0",
      "230": "wailastages 2.0.23",
      "231": "wanionlib 1.12.2-2.2",
      "232": "watercontrolextreme 1.0.0",
      "233": "waterstrainer 3.2.0",
      "234": "wawla 2.5.273",
      "235": "weirdinggadget 1.0",
      "236": "wildcrops 1.0.1",
      "237": "witherskelefix 2.6.3",
      "238": "wopper 1.12-r5",
      "239": "xnet 1.8.1",
      "240": "ynot 0.2.4",
      "241": "yoyos 1.12.2-1.3.0.21",
      "242": "zenstages 0.4.1-19",
      "243": "primal_tech 0.3.4",
      "244": "teslacorelib_registries 1.0.15"
    }
  }
}```

**Comment by kmpm** [comment]
Any chance you could set the environment variable DEBUG to "mcquery:lib:*" and try your application again?
`export DEBUG="mcquery:lib:*"` if you are using linux. 

You should be getting a lot of output from mcquery that would help.

P.S. The external api didn't use the query protocol ( `"query": false` ) to that does not show that query do actually work on the server.

**Comment by kmpm** [comment]
sorry, it should be `DEBUG=mcquery:*`

**Comment by upedd** [comment]
```
mcquery:DEBUG Query#0 _clearSocket +0ms
  mcquery:DEBUG Query#0 created +0ms
  mcquery:DEBUG Query#0 connect +1ms
  mcquery:DEBUG Query#0 _createSocket +1ms
  mcquery:DEBUG Query#0 doing handshake +1ms
  mcquery:DEBUG Query#0 _addQueue() +1ms
  mcquery:DEBUG Query#0 _addQueue > creating timeout +0ms
  mcquery:DEBUG Query#0 _addQueue > adding type 9 to queue +1ms
  mcquery:DEBUG Query#0 _addQueue > outstatndingRequest= 1 +0ms
  mcquery:DEBUG Query#0 _processQueue() +0ms
  mcquery:DEBUG Query#0 _processQueue > queue length 1 +0ms
  mcquery:DEBUG Query#0 _processQueue > processing something on the queue object +0ms
  mcquery:DEBUG Query#0 _transmit(<Buffer fe fd 09 00 00 00 01>) +0ms
  mcquery:DEBUG Query#0 sending packet <Buffer fe fd 09 00 00 00 01> +1ms
  mcquery:DEBUG Query#0 7 bytes sent to localhost:25565 +2ms
  mcquery:DEBUG Query#0 _processQueue() +98ms
  mcquery:DEBUG Query#0 _processQueue > clearing timer +0ms
  mcquery:DEBUG Query#0 _processQueue > nothing to do +0ms
  mcquery:INFO Query#0 _addQueue > timeout on req 1 +0ms
  mcquery:DEBUG Query#0 _addQueue > queue length=0, index=-1 +3s
  mcquery:DEBUG Query#0 _addQueue > length after 0 +0ms
  mcquery:DEBUG Query#0 _addQueue > remove current request +0ms
  mcquery:ERROR Query#0 error in doHandshake Error: Request timeout
    at Timeout._onTimeout (/mnt/c/Users/MiłoszK/Desktop/Programowanie/Discord/server-manager/node_modules/mcquery/lib/index.js:349:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) +0ms
error connecting Error: Request timeout
    at Timeout._onTimeout (/mnt/c/Users/MiłoszK/Desktop/Programowanie/Discord/server-manager/node_modules/mcquery/lib/index.js:349:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Now it's on local server because friend is playing with the other one.

**Comment by upedd** [comment]
Wait it's actually working on the local server i had query disabled on local one. Going to send the log from the other one.

**Comment by upedd** [comment]
```
mcquery:DEBUG Query#0 _clearSocket +0ms
  mcquery:DEBUG Query#0 created +1ms
Connecting to server
  mcquery:DEBUG Query#0 connect +0ms
  mcquery:DEBUG Query#0 _createSocket +1ms
  mcquery:DEBUG Query#0 doing handshake +1ms
  mcquery:DEBUG Query#0 _addQueue() +1ms
  mcquery:DEBUG Query#0 _addQueue > creating timeout +0ms
  mcquery:DEBUG Query#0 _addQueue > adding type 9 to queue +0ms
  mcquery:DEBUG Query#0 _addQueue > outstatndingRequest= 1 +1ms
  mcquery:DEBUG Query#0 _processQueue() +0ms
  mcquery:DEBUG Query#0 _processQueue > queue length 1 +0ms
  mcquery:DEBUG Query#0 _processQueue > processing something on the queue object +0ms
  mcquery:DEBUG Query#0 _transmit(<Buffer fe fd 09 00 00 00 01>) +0ms
  mcquery:DEBUG Query#0 sending packet <Buffer fe fd 09 00 00 00 01> +0ms
  mcquery:DEBUG Query#0 7 bytes sent to 35.242.214.235:25565 +1ms
  mcquery:DEBUG Query#0 _processQueue() +100ms
  mcquery:DEBUG Query#0 _processQueue > clearing timer +0ms
  mcquery:DEBUG Query#0 _processQueue > nothing to do +1ms
  mcquery:INFO Query#0 _addQueue > timeout on req 1 +0ms
  mcquery:DEBUG Query#0 _addQueue > queue length=0, index=-1 +3s
  mcquery:DEBUG Query#0 _addQueue > length after 0 +0ms
  mcquery:DEBUG Query#0 _addQueue > remove current request +0ms
  mcquery:ERROR Query#0 error in doHandshake Error: Request timeout
    at Timeout._onTimeout (/mnt/c/Users/MiłoszK/Desktop/Programowanie/Discord/server-manager/node_modules/mcquery/lib/index.js:349:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) +0ms
error connecting Error: Request timeout
    at Timeout._onTimeout (/mnt/c/Users/MiłoszK/Desktop/Programowanie/Discord/server-manager/node_modules/mcquery/lib/index.js:349:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Still throws an error this time i am sure the query is running
`[15:35:46] [Query Listener #1/INFO] [minecraft/MinecraftServer]: Query running on 0.0.0.0:25565`

**Comment by upedd** [comment]
Finally i found out query works thru UDP while i was only exposing port 25565 thru TCP.

**Comment by kmpm** [comment]
Is there a firewall used in the setup? If so, is it open for UDP?
It looks as if the server doesn't get the request.

**Comment by upedd** [comment]
lol, we commented the same thing at the same time.

**Comment by kmpm** [comment]
God thing it got solved.
